### ISSUE TITLE
i am getting TypeError: BrowseCarouselItem is not a constructor in dialogflow

### ISSUE THREAD

**Issue by kumaresan93** [MishUshakov/dialogflow-web#69]
TypeError: BrowseCarouselItem is not a constructor
    at Destination (/user_code/index.js:42:9)
    at WebhookClient.handleRequest (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:303:44)
    at exports.dialogflowFirebaseFulfillment.functions.https.onRequest (/user_code/index.js:81:9)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:57:9)
    at /var/tmp/worker/worker.js:724:7
    at /var/tmp/worker/worker.js:707:11
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by MishUshakov** [comment]
Not a web client issue
